spring:
  h2:
    console:
      enabled: true
      path: /console
  datasource:
    url: jdbc:h2:file:C:\\Users\\marci\\Desktop\\Development\\todo-app\\todo-db
  jpa:
    hibernate:
      ddl-auto: update
task:
  template:
    allowMultipleTasks: false